### ISSUE TITLE
popTo() has not been attached yet

### ISSUE THREAD

**Issue by luziqi123** [YoKeyword/Fragmentation#1265]
在使用最新版的时候调用popTo()方法报出了 has not been attached yet 错误。
一点一点debug发现在onHiddenChanged的时候调用了一个 onFragmentShownWhenNotResumed() 方法。在这个方法调用了mFragment.getChildFragmentManager(); 然而在之前的一大堆方法调用中已经触发Fragment的mHose = null的操作了，所以就报错了。。
我目前的解决办法是在前面做一个判断，现在我的VisibleDelegate.java下dispatchChildOnFragmentShownWhenNotResumed方法长这样儿：
```
    private void dispatchChildOnFragmentShownWhenNotResumed() {
        if (!mFragment.isAdded()) {
            return;
        }
        FragmentManager fragmentManager = mFragment.getChildFragmentManager();
        List<Fragment> childFragments = fragmentManager.getFragments();
        if (childFragments != null) {
            for (Fragment child : childFragments) {
                if (child instanceof ISupportFragment && !child.isHidden() && child.getUserVisibleHint()) {
                    ((ISupportFragment) child).getSupportDelegate().getVisibleDelegate().onFragmentShownWhenNotResumed();
                }
            }
        }
    }
```

**Comment by chenyao1208** [comment]
请问大佬上述代码要加在哪个地方，我全局搜索没有找到VisibleDelegate相关的类啊，望指点

**Comment by chenyao1208** [comment]
请问大佬上述代码要加在哪个地方，我全局搜索没有找到VisibleDelegate相关的类啊，望指点

**Comment by n272367953** [comment]
大佬这个库都不维护了


***@***.***
 
From: chenyao
Date: 2021-08-23 14:14
To: YoKeyword/Fragmentation
CC: Subscribed
Subject: Re: [YoKeyword/Fragmentation] popTo() has not been attached yet (#1265)
请问大佬上述代码要加在哪个地方，我全局搜索没有找到VisibleDelegate相关的类啊，望指点
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by luziqi123** [comment]
> 请问大佬上述代码要加在哪个地方，我全局搜索没有找到VisibleDelegate相关的类啊，望指点
